services:
  coturn:
    image: coturn/coturn
    container_name: fileferry-coturn
    restart: always
    network_mode: host
    # ports:
    #   - '3478:3478'
    #   - '49152-49352:49152-49352'
    volumes:
      - /home/smp/FileFerry/relay-server/my-turnserver.conf:/etc/coturn/turnserver.conf:ro
    read_only: true
    tmpfs:
      - /var/lib/coturn
    # networks:
    #   - coturn-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3072M

  passphrase-server:
    image: passphrase-server
    container_name: fileferry-passphrase-server
    restart: always
    ports:
      - '8081:8080/tcp'
    networks:
      - passphrase-net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  relay-server:
    image: relay-server
    container_name: fileferry-relay-server
    restart: always
    env_file:
      - /home/smp/FileFerry/relay-server/.env
    volumes:
      - relay-data:/app/db
    network_mode: host
    read_only: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  geoip-api:
    image: geoip-api:latest
    ports:
      - '8000:8000'
    volumes:
      - geoip-data:/app/api/db
    environment:
      - ENVIRONMENT=production
    read_only: true
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M

networks:
  coturn-net:
    driver: bridge
    name: coturn-net
  passphrase-net:
    driver: bridge
    name: passphrase-net
  relay-net:
    driver: bridge
    name: relay-net

volumes:
  geoip-data:
  relay-data:
