# Credentianls
lt-cred-mech

# !! EDIT THESE VALUES !!
user=username:password
realm=relay.example.com

# Logging (send to stdout for Docker to handle)
verbose

# Security
stale-nonce=600
no-loopback-peers
no-multicast-peers

# Ports for relaying 
min-port=49152
max-port=49352

# Resource limits
user-quota=200
total-quota=1200
