# Workflow for deploying static content to GitHub Pages
name: Deploy Static Content to Pages

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'pages-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for Staging Branch
        if: github.ref == 'refs/heads/staging'
        run: npm run build:staging

      - name: Build for Main Branch (Production)
        if: github.ref == 'refs/heads/main'
        run: npm run build

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: dist
          target-folder:
            ${{ github.ref == 'refs/heads/staging' && 'staging' || '.' }}
          clean: true
          clean-exclude: |
            staging
